# ・依頼コメント
# Go言語のWebAPIを実行するためのDockerComposeファイルを書いてもらえる？
# MySQLをデータベースに使うよ
version: '3'
services:
  api:
    image: golang:latest
    ports:
      - "5001:5001"
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - PORT=5001
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PORT=3306
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=public
    volumes:
      - ./:/go/src/app
    working_dir: /go/src/app
    command: go run main.go
  web:
    image: node:16
    command: npm run serve
    volumes:
      - ./twitter:/app
    ports:
      - "8080:8080"
    working_dir: /app
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=public
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
